### ISSUE TITLE
아이콘이 사라짐

### ISSUE THREAD

**Issue by star0202** [yjdevs/infomaker#1]
IDE에서 실행하면 아이콘이 적용되지만,
직접 파일을 눌러 실행하면 아이콘이 적용되지 않는다
IDE:
![image](https://user-images.githubusercontent.com/61998307/124274645-7cbb2800-db7c-11eb-8a93-146882503114.png)
직접 누름:
![image](https://user-images.githubusercontent.com/61998307/124274678-86dd2680-db7c-11eb-8fa0-a3544c2b3d95.png)

**Comment by star0202** [comment]
이제는 IDE에서도 안보이는....

**Comment by mvp-11235** [comment]
UI코드를 봤을 때 아이콘파일을 '.'으로 시작해야 하는데 '.'을 쓰지 않아서 IDE에서 나오지 않았음.
![image](https://user-images.githubusercontent.com/84168388/124349959-b9465c80-dc2c-11eb-999e-9be56abc1fde.png)
